"""initial tables

Revision ID: 06900ae2791f
Revises: 
Create Date: 2026-03-03 08:39:17.261268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06900ae2791f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_natural', sa.String(length=255), nullable=False),
    sa.Column('nombre_cientifico', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('subcategoria', sa.String(length=100), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimiento', sa.String(length=10), nullable=False),
    sa.Column('origen', sa.String(length=30), nullable=False),
    sa.Column('origen_zona', sa.String(length=50), nullable=True),
    sa.Column('destino', sa.String(length=30), nullable=False),
    sa.Column('destino_zona', sa.String(length=50), nullable=True),
    sa.Column('destino_distrito', sa.String(length=100), nullable=True),
    sa.Column('destino_barrio', sa.String(length=100), nullable=True),
    sa.Column('destino_direccion', sa.String(length=255), nullable=True),
    sa.Column('tamano_inicial', sa.Integer(), nullable=False),
    sa.Column('tamano_final', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos')
    op.drop_table('productos')
    # ### end Alembic commands ###
