"""add pedidos

Revision ID: 671644fc3faf
Revises: ef7b7479b0a3
Create Date: 2026-03-05 11:09:55.813350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '671644fc3faf'
down_revision: Union[str, Sequence[str], None] = 'ef7b7479b0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_username', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('served_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('served_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_estado'), 'pedidos', ['estado'], unique=False)
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_solicitante_username'), 'pedidos', ['solicitante_username'], unique=False)
    op.create_table('pedido_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_items_id'), 'pedido_items', ['id'], unique=False)
    op.create_index(op.f('ix_pedido_items_pedido_id'), 'pedido_items', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_items_producto_id'), 'pedido_items', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_items_producto_id'), table_name='pedido_items')
    op.drop_index(op.f('ix_pedido_items_pedido_id'), table_name='pedido_items')
    op.drop_index(op.f('ix_pedido_items_id'), table_name='pedido_items')
    op.drop_table('pedido_items')
    op.drop_index(op.f('ix_pedidos_solicitante_username'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_estado'), table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
