"""tabla usuarios

Revision ID: ef7b7479b0a3
Revises: 59a2b869b12e
Create Date: 2026-03-04 09:39:09.704205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef7b7479b0a3'
down_revision: Union[str, Sequence[str], None] = '59a2b869b12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.alter_column('productos', 'nombre_natural',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('uq_productos_nombre_cientifico_norm'), table_name='productos', postgresql_where="(NULLIF(btrim((nombre_cientifico)::text), ''::text) IS NOT NULL)")
    op.drop_index(op.f('uq_productos_nombre_natural_norm'), table_name='productos', postgresql_where="(NULLIF(btrim((nombre_natural)::text), ''::text) IS NOT NULL)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_productos_nombre_natural_norm'), 'productos', [sa.literal_column('lower(btrim(nombre_natural::text))')], unique=True, postgresql_where="(NULLIF(btrim((nombre_natural)::text), ''::text) IS NOT NULL)")
    op.create_index(op.f('uq_productos_nombre_cientifico_norm'), 'productos', [sa.literal_column('lower(btrim(nombre_cientifico::text))')], unique=True, postgresql_where="(NULLIF(btrim((nombre_cientifico)::text), ''::text) IS NOT NULL)")
    op.alter_column('productos', 'nombre_natural',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
